// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profiles.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProfile = `-- name: CreateProfile :exec
INSERT INTO profiles (account_id, account_type)
VALUES ($1, $2)
ON CONFLICT (account_id) DO NOTHING
`

type CreateProfileParams struct {
	AccountID   pgtype.UUID `json:"account_id"`
	AccountType AccountType `json:"account_type"`
}

// Idempotent: a redelivered account.created event leaves the existing profile unchanged.
func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) error {
	_, err := q.db.Exec(ctx, createProfile, arg.AccountID, arg.AccountType)
	return err
}

const getProfileByAccountID = `-- name: GetProfileByAccountID :one
SELECT account_id, account_type, full_name, phone, locale, created_at, updated_at FROM profiles
WHERE account_id = $1
`

func (q *Queries) GetProfileByAccountID(ctx context.Context, accountID pgtype.UUID) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfileByAccountID, accountID)
	var i Profile
	err := row.Scan(
		&i.AccountID,
		&i.AccountType,
		&i.FullName,
		&i.Phone,
		&i.Locale,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
