// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Idempotent: a redelivered account.created event leaves the existing profile unchanged.
	CreateProfile(ctx context.Context, arg CreateProfileParams) error
	GetProfileByAccountID(ctx context.Context, accountID pgtype.UUID) (Profile, error)
}

var _ Querier = (*Queries)(nil)
