// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (email, password_hash)
VALUES ($1, $2)
RETURNING id, email, password_hash, status, email_verified_at, failed_login_attempts, locked_until, banned_until, ban_reason, last_login_at, created_at, updated_at
`

type CreateAccountParams struct {
	Email        pgtype.Text `json:"email"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.Email, arg.PasswordHash)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.BannedUntil,
		&i.BanReason,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAuthIdentity = `-- name: CreateAuthIdentity :one
INSERT INTO auth_identities (account_id, provider, provider_user_id, provider_email)
VALUES ($1, $2, $3, $4)
RETURNING id, account_id, provider, provider_user_id, provider_email, created_at, last_used_at
`

type CreateAuthIdentityParams struct {
	AccountID      pgtype.UUID  `json:"account_id"`
	Provider       AuthProvider `json:"provider"`
	ProviderUserID string       `json:"provider_user_id"`
	ProviderEmail  pgtype.Text  `json:"provider_email"`
}

func (q *Queries) CreateAuthIdentity(ctx context.Context, arg CreateAuthIdentityParams) (AuthIdentity, error) {
	row := q.db.QueryRow(ctx, createAuthIdentity,
		arg.AccountID,
		arg.Provider,
		arg.ProviderUserID,
		arg.ProviderEmail,
	)
	var i AuthIdentity
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Provider,
		&i.ProviderUserID,
		&i.ProviderEmail,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getAccountByAuthIdentity = `-- name: GetAccountByAuthIdentity :one
SELECT a.id, a.email, a.password_hash, a.status, a.email_verified_at, a.failed_login_attempts, a.locked_until, a.banned_until, a.ban_reason, a.last_login_at, a.created_at, a.updated_at FROM accounts a
JOIN auth_identities i ON i.account_id = a.id
WHERE i.provider = $1
  AND i.provider_user_id = $2
`

type GetAccountByAuthIdentityParams struct {
	Provider       AuthProvider `json:"provider"`
	ProviderUserID string       `json:"provider_user_id"`
}

func (q *Queries) GetAccountByAuthIdentity(ctx context.Context, arg GetAccountByAuthIdentityParams) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByAuthIdentity, arg.Provider, arg.ProviderUserID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.BannedUntil,
		&i.BanReason,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByEmail = `-- name: GetAccountByEmail :one
SELECT id, email, password_hash, status, email_verified_at, failed_login_attempts, locked_until, banned_until, ban_reason, last_login_at, created_at, updated_at FROM accounts
WHERE lower(email) = lower($1)
`

func (q *Queries) GetAccountByEmail(ctx context.Context, lower string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByEmail, lower)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.BannedUntil,
		&i.BanReason,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, email, password_hash, status, email_verified_at, failed_login_attempts, locked_until, banned_until, ban_reason, last_login_at, created_at, updated_at FROM accounts
WHERE id = $1
`

func (q *Queries) GetAccountByID(ctx context.Context, id pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.BannedUntil,
		&i.BanReason,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markEmailVerified = `-- name: MarkEmailVerified :exec
UPDATE accounts
SET email_verified_at = now(),
    status = 'active',
    updated_at = now()
WHERE id = $1
`

func (q *Queries) MarkEmailVerified(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markEmailVerified, id)
	return err
}

const recordFailedLogin = `-- name: RecordFailedLogin :exec
UPDATE accounts
SET failed_login_attempts = failed_login_attempts + 1,
    locked_until = $2,
    updated_at = now()
WHERE id = $1
`

type RecordFailedLoginParams struct {
	ID          pgtype.UUID        `json:"id"`
	LockedUntil pgtype.Timestamptz `json:"locked_until"`
}

func (q *Queries) RecordFailedLogin(ctx context.Context, arg RecordFailedLoginParams) error {
	_, err := q.db.Exec(ctx, recordFailedLogin, arg.ID, arg.LockedUntil)
	return err
}

const recordSuccessfulLogin = `-- name: RecordSuccessfulLogin :exec
UPDATE accounts
SET failed_login_attempts = 0,
    locked_until = NULL,
    last_login_at = now(),
    updated_at = now()
WHERE id = $1
`

func (q *Queries) RecordSuccessfulLogin(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, recordSuccessfulLogin, id)
	return err
}

const setAccountBan = `-- name: SetAccountBan :exec
UPDATE accounts
SET banned_until = $2,
    ban_reason = $3,
    updated_at = now()
WHERE id = $1
`

type SetAccountBanParams struct {
	ID          pgtype.UUID        `json:"id"`
	BannedUntil pgtype.Timestamptz `json:"banned_until"`
	BanReason   pgtype.Text        `json:"ban_reason"`
}

func (q *Queries) SetAccountBan(ctx context.Context, arg SetAccountBanParams) error {
	_, err := q.db.Exec(ctx, setAccountBan, arg.ID, arg.BannedUntil, arg.BanReason)
	return err
}

const setAccountStatus = `-- name: SetAccountStatus :exec
UPDATE accounts
SET status = $2,
    updated_at = now()
WHERE id = $1
`

type SetAccountStatusParams struct {
	ID     pgtype.UUID   `json:"id"`
	Status AccountStatus `json:"status"`
}

func (q *Queries) SetAccountStatus(ctx context.Context, arg SetAccountStatusParams) error {
	_, err := q.db.Exec(ctx, setAccountStatus, arg.ID, arg.Status)
	return err
}
