// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertOutboxEvent = `-- name: InsertOutboxEvent :one
INSERT INTO outbox_events (aggregate_id, event_type, payload)
VALUES ($1, $2, $3)
RETURNING id, aggregate_id, event_type, payload, created_at, published_at
`

type InsertOutboxEventParams struct {
	AggregateID pgtype.UUID `json:"aggregate_id"`
	EventType   string      `json:"event_type"`
	Payload     []byte      `json:"payload"`
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, insertOutboxEvent, arg.AggregateID, arg.EventType, arg.Payload)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.AggregateID,
		&i.EventType,
		&i.Payload,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const listUnpublishedOutboxEvents = `-- name: ListUnpublishedOutboxEvents :many
SELECT id, aggregate_id, event_type, payload, created_at, published_at FROM outbox_events
WHERE published_at IS NULL
ORDER BY id
LIMIT $1
FOR UPDATE SKIP LOCKED
`

func (q *Queries) ListUnpublishedOutboxEvents(ctx context.Context, limit int32) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, listUnpublishedOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEvent
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.AggregateID,
			&i.EventType,
			&i.Payload,
			&i.CreatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxEventPublished = `-- name: MarkOutboxEventPublished :exec
UPDATE outbox_events
SET published_at = now()
WHERE id = $1
`

func (q *Queries) MarkOutboxEventPublished(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markOutboxEventPublished, id)
	return err
}
