// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (account_id, refresh_token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, account_id, refresh_token_hash, created_at, expires_at, revoked_at
`

type CreateSessionParams struct {
	AccountID        pgtype.UUID        `json:"account_id"`
	RefreshTokenHash []byte             `json:"refresh_token_hash"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.AccountID, arg.RefreshTokenHash, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.RefreshTokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getSessionByRefreshHash = `-- name: GetSessionByRefreshHash :one
SELECT id, account_id, refresh_token_hash, created_at, expires_at, revoked_at FROM sessions
WHERE refresh_token_hash = $1
`

func (q *Queries) GetSessionByRefreshHash(ctx context.Context, refreshTokenHash []byte) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByRefreshHash, refreshTokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.RefreshTokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeAccountSessions = `-- name: RevokeAccountSessions :exec
UPDATE sessions
SET revoked_at = now()
WHERE account_id = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeAccountSessions(ctx context.Context, accountID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAccountSessions, accountID)
	return err
}

const revokeSession = `-- name: RevokeSession :execrows
UPDATE sessions
SET revoked_at = now()
WHERE id = $1
  AND revoked_at IS NULL
`

// Returns the number of rows changed. Zero means the session was already revoked, which
// the caller must treat as a reused token.
func (q *Queries) RevokeSession(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSession, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
