// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: verifications.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeEmailVerification = `-- name: ConsumeEmailVerification :one
UPDATE email_verifications
SET used_at = $1::timestamptz
WHERE token_hash = $2
  AND used_at IS NULL
  AND expires_at > $1::timestamptz
RETURNING account_id
`

type ConsumeEmailVerificationParams struct {
	NowAt     pgtype.Timestamptz `json:"now_at"`
	TokenHash []byte             `json:"token_hash"`
}

// Marks the token used and returns its account. No row means the token is unknown, already
// used, or expired, and the caller must refuse it without saying which. The current time is
// passed in, so expiry follows the service's clock.
func (q *Queries) ConsumeEmailVerification(ctx context.Context, arg ConsumeEmailVerificationParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, consumeEmailVerification, arg.NowAt, arg.TokenHash)
	var account_id pgtype.UUID
	err := row.Scan(&account_id)
	return account_id, err
}

const createEmailVerification = `-- name: CreateEmailVerification :one
INSERT INTO email_verifications (account_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, account_id, token_hash, created_at, expires_at, used_at
`

type CreateEmailVerificationParams struct {
	AccountID pgtype.UUID        `json:"account_id"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateEmailVerification(ctx context.Context, arg CreateEmailVerificationParams) (EmailVerification, error) {
	row := q.db.QueryRow(ctx, createEmailVerification, arg.AccountID, arg.TokenHash, arg.ExpiresAt)
	var i EmailVerification
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const invalidateEmailVerifications = `-- name: InvalidateEmailVerifications :exec
UPDATE email_verifications
SET used_at = now()
WHERE account_id = $1
  AND used_at IS NULL
`

// Used before a new link is issued, so only the newest link works.
func (q *Queries) InvalidateEmailVerifications(ctx context.Context, accountID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, invalidateEmailVerifications, accountID)
	return err
}
